### ISSUE TITLE
Missing header `slsReceiverUsers.h`

### ISSUE THREAD

**Issue by sdebionne** [slsdetectorgroup/sls_detector_lib#1]
Hello,
I have just installed the 4.0.1 conda package with `conda install -c slsdetectorgroup sls_detector_lib` but could not find `slsReceiverUsers.h` in the environment, is this header deprecated?

**Comment by erikfrojdh** [comment]
Eh no... but it seems to have been left out by mistake. Corrected in 4.0.1 build nr 1.
Sorry for that
